### ISSUE TITLE
Маги воды бегают по вейпоинтам в Яркендаре

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#403]
Раньше вальяжно ходили между точками ожидания, теперь суетливо бегают. Стоит humans remaster, если это может повлиять

**Comment by dosinabox** [comment]
У меня ходят спокойно и расписание ZS_Study_WP такое же как в оригинале, с AI_SetWalkMode(self,NPC_WALK). Есть сохраненка?

**Comment by dosinabox** [comment]
<img width="449" alt="Screenshot_1" src="https://user-images.githubusercontent.com/39790055/145246070-1db6ee8f-cc58-41db-ba46-72efaa7ff83b.png">

**Comment by Kor-Angar** [comment]
Они раньше бегать начинали после того как атакуют богомола.19:31, 8 декабря 2021 г., dosinabox ***@***.***>:


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by LDS1** [comment]
Глянул старый сейв и тоже ходят. 

Похоже было какое-то условие для этого, но беготня сохранялась надолго. 
Те телепортировался из другой части addonworld, а они все еще бегали. Сохранения/загрузки тоже не прерывали эффект

**Comment by dosinabox** [comment]
Мне казалось что они всегда бегали, даже в оригинале. То ли память подводит, то ли есть ещё какие-то условия. Но в памяти у меня это точно есть.
