### ISSUE TITLE
Ли требует деньги за избиение наемников

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#404]
Если избить наемника без честной дуэли(а может и с ней), то Ли потом жалуется, что я избиваю крестьян и требует деньги.

**Comment by Kor-Angar** [comment]
а если избить наёмника не на глазах у крестьян?

**Comment by LDS1** [comment]
не знаю, нужно тестить

**Comment by dosinabox** [comment]
Какого именно наемника? Не получается воспоизвести.

**Comment by LDS1** [comment]
У меня сейвов этих уже нет. Помню, что не трогал крестьян, а бил только людей Сильвио, а Ли потом требовал деньги.

**Comment by LDS1** [comment]
Год назад играл та же история была

**Comment by Kor-Angar** [comment]
> Какого именно наемника? Не получается воспоизвести.

при крестьянах бить наёмников нельзя. если крестьяни видят то Ли начисляет штраф. если крестьяне не видят не начисляет.
Ли не будет начислять штраф если видили крестьяне, но это была "дуэль".

**Comment by dosinabox** [comment]
> при крестьянах бить наёмников нельзя. если крестьяни видят то Ли начисляет штраф.

Даже такое не получается воспроизвести. Атакую всех наемников, крестьяне пугаются и ничего не делают, у Ли штрафа нет. Если атакую крестьян, то наемники вступаются, а Ли требует штраф.

**Comment by Kor-Angar** [comment]
проверь фракцию

**Comment by dosinabox** [comment]
у всех жителей фермы правильные фракции

**Comment by Kor-Angar** [comment]
значит ты это правила в этом или прошлом году

**Comment by Kor-Angar** [comment]
значит ты это уже правила в этом или прошлом году. была схожая проблема и мы что то обсуждали за дуэли

**Comment by LDS1** [comment]
Баг поймал пару дней назад на самом последнем стимфиксе

**Comment by dosinabox** [comment]
Может, это был Альварес или Энгардо?

**Comment by LDS1** [comment]
Кто-то из стандартных людей Сильвио в первой главе на этапе вступления.

**Comment by Kor-Angar** [comment]
нейтрал? квест Ярвиса был взять?

**Comment by LDS1** [comment]
Нейтрал, насколько помню квест еще не был взят.

**Comment by Kor-Angar** [comment]
@dosinabox може правила дуэли на это как то влияют? у тебя же где то там была проверка на то знает ли герой  правила дуэли(торлоф/ярвис)..

**Comment by dosinabox** [comment]
Проблема действительно в крестьянах-свидетелях, которые при виде драки переходят в состояние ZS_WatchFight, а при нокауте наемника запоминают преступление не учитывая C_NpcIsToughGuy жертвы, если драка не была дуэльной. При этом штрафа не будет, если вырубить наемника с одного удара, потому что свидетели не успеют перейти в состояние наблюдения за дракой.

```cpp
func void B_AssessDefeat()
{
	Npc_ClearAIQueue(self);
	if(C_NpcIsToughGuy(self) || (Npc_IsPlayer(other) && (self.npcType == NPCTYPE_FRIEND)))
	{
		if(Npc_GetAttitude(self,other) == ATT_FRIENDLY)
		{
			B_Say(self,other,"$GOODVICTORY");
		}
		else
		{
			B_Say(self,other,"$NOTBAD");
		};
	}
	else if(victim.aivar[AIV_ATTACKREASON] != AR_NONE)
	{
		B_Say(self,other,"$OHMYGODHESDOWN");
		//нет проверки!
		B_MemorizePlayerCrime(self,other,CRIME_ATTACK);
	}
	else
	{
		B_Say(self,other,"$NOTBAD");
	};
};
```

**Comment by dosinabox** [comment]
И всё же, что тут нужно сделать? Разделение жертв на крестьян/наемников и новую озвучку Ли, или не запоминать такие драки с наемниками?

**Comment by LDS1** [comment]
Тк наемники это куча свободолюбивых головорезов и Ли напрямую заявляет, что под защитой только крестьяне, думаю стоит игнорировать любые стычки с наемниками.

**Comment by dosinabox** [comment]
Похожая ситуация возможна в Хоринисе: если обычный горожанин услышит драку ГГ с портовым жителем, то настучит Андрэ/Хагену. Или если дерущиеся перейдут из портового квартала во время драки. Тоже не понятно, правильно ли это)

**Comment by Kor-Angar** [comment]
Хз. Я в своей сборке просто добавил возможность вызвать неименного наёмник на дуэль. Таким образом оно и  соответствуют ЛОРу и решает данную проблему.  Избиение наемников недуэльное на мой взгляд не самая адекватная механика. Если это не дуэль, то по идеи другие наёмники вообще должны агриться. 18:26, 8 декабря 2021 г., dosinabox ***@***.***>:
И всё же, что тут нужно сделать? Разделение жертв на крестьян/наемников и новую озвучку Ли, или не запоминать такие драки с наемниками?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Если это не дуэль, то по идеи другие наёмники вообще должны агриться.

Так и есть. Но положен ли за это штраф у Ли?

**Comment by Kor-Angar** [comment]
Хз. Можно штраф начислять в зависимости от фракции. Например штрафовать другие фракции, так как Наёмники все таки наняты Онаром и ему может не понравиться такое поведение милиционера. Можно перечатать диалоги наемников неименных и крестьян у кого то из них по моему была какая то информация про штрафы.  Может станет понятнее. 18:33, 8 декабря 2021 г., dosinabox ***@***.***>:

Если это не дуэль, то по идеи другие наёмники вообще должны агриться.

Так и есть. Но положен ли за это штраф у Ли?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by LDS1** [comment]
Зачем выдумывать требования, можно просто заглянуть в диалог с Ли. Насколько я помню он напрямую заявляет, что делай с наемниками что хочешь вообще, крестьян только не трожь, он за них отвечает.

**Comment by Kor-Angar** [comment]
Это он говорит кандидату в наёмнику или ополченцы?Что он говорит герою ополченцы который пришёл первый раз на ферму? 😀18:41, 8 декабря 2021 г., Dmitriy Luganskiy ***@***.***>:
Зачем выдумывать требования, можно просто заглянуть в диалог с Ли. Насколько я помню он напрямую заявляет, что делай с наемниками что хочешь вообще, крестьян только не трожь, он за них отвечает.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Собственно, простая атака без причины вызывает агрессию всех наемников вокруг, а дуэль проходит 1 на 1. В обоих случаях штрафы не нужны, ещё и с неправильной озвучкой Ли.

**Comment by dosinabox** [comment]
```cpp
AI_Output(self,other,"DIA_Lee_PETZMASTER_04_12");	//Если ты обвиняешься в дуэли с наемником, это одно...
AI_Output(self,other,"DIA_Lee_PETZMASTER_04_13");	//Но если ты избил фермера, они сразу бегут к Онару. И он ожидает определенных действий от меня.

AI_Output(self,other,"DIA_Lee_PMSchulden_04_08");	//Не осталось никого, кто видел бы, как ты избил одного из фермеров.
```

**Comment by dosinabox** [comment]
Вот только Беннет тоже наемник) За драку с ним надо бы штрафовать, наверное. Или нет?

**Comment by LDS1** [comment]
Может его в крестьян понизить? Или он с какой-то целью в наемниках?

**Comment by Kor-Angar** [comment]
Беннет бессмертный 😀18:58, 8 декабря 2021 г., dosinabox ***@***.***>:
Вот только Беннет тоже наемник) За драку с ним надо бы штрафовать, наверное. Или нет?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты
