### ISSUE TITLE
Эффект Глаза Инноса полностью исчезает после разговора с драконом

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#406]
Глаз должен защищать от огня дракона и тд, но сразу после разговора он не только теряет способность заставить дракона говорить, но и все бонусы к защите.

**Comment by Kor-Angar** [comment]
Такие вот нестыковки в ЛОРе. Глаз защищает от огня дракона, но после разговора теряет свою силу. 2:07, 8 декабря 2021 г., Dmitriy Luganskiy ***@***.***>:
Глаз должен защищать от огня дракона и тд, но сразу после разговора он не только теряет способность заставить дракона говорить, но и все бонусы к защите.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by LDS1** [comment]
Я к тому, что было бы классно это поправить ;)

**Comment by Kor-Angar** [comment]
Это не возможно поправить с точки зрения баланса 😀 у дракона итак более низкий ущерб у ищущих в 4 главе. Правки глаза приводит к правкам драконов что приведёт к правкам баланса 😀5:08, 8 декабря 2021 г., Dmitriy Luganskiy ***@***.***>:
Я к тому, что было бы классно это поправить ;)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by LDS1** [comment]
Драконы по сути инкапсулированы относительно остального баланса. Ты с ними должен драться только с глазом и только в 4й главе. Кмк им можно тупо поднять урон огнем, чтобы перекрыть действие глаза. Заодно они станут реально страшными без него.

**Comment by Kor-Angar** [comment]
ты говоришь про правку баланса. так перед драконом вместо глаза одеваю амулет на защиту от огня или магии, а с твоим предложением драконы фактически станут сильнее, если даже герой будет с глазом.

**Comment by Kor-Angar** [comment]
> Ты с ними должен драться только с глазом и только в 4й главе. 

что бы с ними поговорить нужно иметь глаз. речь же идёт о допросе дракона, который и разряжает глаз.

**Comment by LDS1** [comment]
Сейчас глаз не работает во время боя с драконом. Те если увеличить урон огнем на 20-30(или сколько там глаз дает), то оно так и выйдет, не нужно будет экипать другие амулеты и глаз будет выполнять заявленную лором функцию

**Comment by LDS1** [comment]
Если что - я их бил в ближнем без всяких доп амулетов до того, как заметил баг, нормально падали.

**Comment by Kor-Angar** [comment]
а это здесь при чём? ну бил ты их , ну падали они нормально. разве это повод править баланс?

**Comment by LDS1** [comment]
фокус в том, что баланс можно не править ;) 

даже если захочешь им поднять урон огнем, это никак на остальную игру не повлияет

но по сути баг репорт про отсутсвие защиты от глаза

**Comment by Kor-Angar** [comment]
> и глаз будет выполнять заявленную лором функцию

ЛОРная функция глаза заставить заговорить дракона, после чего глаз разряжается.

    ```D
    B_AI_Output(other,self,"DIA_Pyrokar_KAP3_READY_15_00");   //Что мне остается сделать здесь?
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_01");   //Не трать свое время на тривиальные вещи. Иди и уничтожь драконов. Вот, возьми Глаз.
        CreateInvItems(self,itmi_innoseye_mis,1);
        b_giveinvitems(self,other,itmi_innoseye_mis,1);
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_02");   //Помни, что тебе нужно сначала поговорить с драконом, прежде чем ты сможешь атаковать его.
        B_AI_Output(self,other,"DIA_Pyrokar_Add_11_01");  //Сила Глаза заставит драконов говорить с тобой, и говорить правду.
        B_AI_Output(self,other,"DIA_Pyrokar_Add_11_02");  //Кроме того, он дает защиту от их атак.
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_05");   //Однако, его сила не вечна. Тебе придется снова пополнять его магической энергией.
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_06");   //Для этого тебе понадобится эссенция из сердца дракона, которую нужно объединить с Глазом на алхимическом столе.
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_07");   //Только тогда ты сможешь приблизиться к очередному дракону.
        B_AI_Output(other,self,"DIA_Pyrokar_KAP3_READY_15_08");   //Спасибо. Я запомню это.
        B_AI_Output(self,other,"DIA_Pyrokar_KAP3_READY_11_09");   //Теперь у тебя есть все необходимое. Иди же. У тебя не так много времени.
        PLAYER_TALENT_ALCHEMY[CHARGE_INNOSEYE] = TRUE;
        PrintScreen(PRINT_LEARNALCHEMYINNOSEYE,-1,-1,FONT_SCREEN,2);
        TOPIC_END_INNOSEYE = TRUE;
        b_giveplayerxp(XP_AMBIENT);
        CreateInvItems(gorax,itmi_runeblank,1);
        Log_CreateTopic(TOPIC_DRACHENJAGD,LOG_MISSION);
        Log_SetTopicStatus(TOPIC_DRACHENJAGD,LOG_RUNNING);
        b_logentry(TOPIC_DRACHENJAGD,TOPIC_DRACHENJAGD_description_178); // "Теперь я готов к встрече с драконами. Глаз Инноса поможет мне уничтожить их. Но прежде чем вступать в битву с драконами я должен не забыть надеть его. Я должен поговорить с драконами прежде чем начинать сражение. Проблема состоит в том что Глаз теряет свою силу каждый раз когда я разговариваю с одним из них. Чтобы восстановить силу этого амулета мне необходимо сердце дракона и пустая мензурка. Я должен объединить ослабленный камень и экстракт из драконьего сердца на алхимическом столе прежде чем противостоять другому дракону."
```
глаз защищает от огня дракона, когда он заряженный.

**Comment by LDS1** [comment]
Но ты не можешь биться с драконом, если он заряжен. Что-то не складывается, да?

**Comment by Kor-Angar** [comment]
> фокус в том, что баланс можно не править ;)
> даже если захочешь им поднять урон огнем, это никак на остальную игру не повлияет

ты же предлагаешь поправить баланс. если глаз будет защищать героя во время боя, ОнД  может получить защиту от фаерболов при которой они перестанут наносить ему ущерб. сейчас такое возможно только при игре за мага

**Comment by LDS1** [comment]
А ты про фаерболл. Он общий для всех или у драконов отдельный спелл? Если отдельный, то вроде бы все просто.

**Comment by Kor-Angar** [comment]
то есть ты опять говоришь про правку баланса. после которой герой станет получать больше урона :-)

**Comment by LDS1** [comment]
Вся правка баланса = фикс бага с защитой и увеличение дамага огнем у дракона. Или я что-то не понял?

**Comment by Kor-Angar** [comment]
> Что-то не складывается, да?

ваще не складывается. Дед втирал, что глаз так же восстановит утраченные силы героя, ну что то ничего подобного не произошло :-)

```D
        B_AI_Output(other,self,"DIA_Xardas_ARTEFAKT_15_00");      //А что такое этот 'Глаз Инноса'?
        B_AI_Output(self,other,"DIA_Xardas_ARTEFAKT_14_01");      //Это амулет. Легенды гласят, что сам Иннос вложил часть своей силы в этот амулет.
        B_AI_Output(self,other,"DIA_Xardas_ARTEFAKT_14_02");      //Он восстановит часть твоей потерянной силы и поможет нам победить драконов.
        B_AI_Output(self,other,"DIA_Xardas_ARTEFAKT_14_03");      //Также он обладает и другими скрытыми возможностями. Я расскажу тебе больше, когда этот амулет будет у тебя в руках.
```

**Comment by Kor-Angar** [comment]
> Вся правка баланса = фикс бага с защитой и увеличение дамага огнем у дракона. Или я что-то не понял?

нету никакого фикса бага. есть разряженный амулет который не даёт защиты герою. ты хочешь разряженному амулету дать защиту, что бы он вообще ничем не отличался от заряженного. это будет и противоречить ЛОРу игры и приведёт к изменению баланса.

> увеличение дамага огнем у дракона

вот дракон стреляет фаерболом. вот я играю магом. одеваю амулет защиты от магии, одеваю кольца и дракон не может мага пробить фаерболом. если поднять драконом урон на величину защиты глаза инноса, то дракон начнём пробивать мага. 

сейчас у героя есть броня + амулет + пояс + кольца. если дракону поднять урон то герой будет получать больше урона так как вместо амулета он будет носить глаз инноса. таким образом с точки зрения баланса герой будет получать урона больше. при этом если герой оденется например на силу или ловкость, то он начнёт получёт урона значительно больше.

**Comment by LDS1** [comment]
Вроде весь смысл в том, что драконы страшные и для борьбы с ними нужен особый амулет. По итогу он валяется в инвентаре с хламом, нужный только для поговорить. Как-то не очень, да? Именно поэтому выглядит как баг. 

Ок, мы выяснили что вся проблема баланса в том, что маг будет пробиваться фб. Давай подумаем в цифрах. Сколько дает амулет защиты от магии против фб и сколько глаз?

**Comment by Kor-Angar** [comment]
Нет. Весь смысл в том что герой должен выпатать у дракона инфу и для этого нужен глаз. Технически глаз снимает с них иммунку и позволяет вообще победить. По крайней мере я так это воспринимаю. Лор игры прямо указывает на разряду амулета. В коде игры прописано по моему три версии амулета, в сломанной состояние в разряженном состояние и в заряженном состояние. В каких то модах в разряженном состояние понижали показатели защиты амулета. Если ты хочешь подумать в цифрах сделай табличку. Пока будешь делать как раз и узнаешь сколько даёт амулет, пояс и кольца 😀17:43, 8 декабря 2021 г., Dmitriy Luganskiy ***@***.***>:
Вроде весь смысл в том, что драконы страшные и для борьбы с ними нужен особый амулет. По итогу он валяется в инвентаре с хламом, нужный только для поговорить. Как-то не очень, да? Именно поэтому выглядит как баг.
Ок, мы выяснили что вся проблема баланса в том, что маг будет пробиваться фб. Давай подумаем в цифрах. Сколько дает амулет защиты от магии против фб и сколько глаз?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by LDS1** [comment]
@dosinabox Закрой плиз тикет, если не будет взят в работу.

**Comment by Kor-Angar** [comment]
P. S.Мне кстати не кажется что в балансе есть проблемы. При этом я видел проблемы в балансе именно когда его начинали править. Например при игре паладином и одевание вещей на ловкость я успевал убить дракона из лука раньше, чем убьёт меня. В других версия с "фиксом" дракона я был вынужден бегать от дракона стреляя в него. Авторы говорили что именно так и должно быть. Другие авторы считали что битва с драконами должна быть эпичной и длится пол часа.  Кто то запрещал пременение на драконов свитков уменьшить монстров. Кто то запрещал демона призванный атаковать дракона. Относительно недавно что бы заговорить с драконом герой должен был именно одеть глаз иннос. Единого мнения нет. Есть набор вариаций и интерпретаций 😀17:43, 8 декабря 2021 г., Dmitriy Luganskiy ***@***.***>:
Вроде весь смысл в том, что драконы страшные и для борьбы с ними нужен особый амулет. По итогу он валяется в инвентаре с хламом, нужный только для поговорить. Как-то не очень, да? Именно поэтому выглядит как баг.
Ок, мы выяснили что вся проблема баланса в том, что маг будет пробиваться фб. Давай подумаем в цифрах. Сколько дает амулет защиты от магии против фб и сколько глаз?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты
